### PR TITLE
Pull Request #1

### PR DESCRIPTION
**Pull request by peacing**
Pushing all changes to players, teams, rosters, and transactions in fantasy_sport.py as well as tests to tests.py. Not all functions work, will open individual issues to fix remaining bugs

### CODE REVIEW

**Comment by josuebrunel** [comment]
Hello @unpairestgood , i have checked your **pull request** a lil bit. I'm gonna merge it within the day. Thanks again for what you do. This is a very good job :+1: . Keep it up buddy. By the way i'm gonna try the fix the test which doesn't pass.
Have a good day,

**Comment by josuebrunel** [comment]
By the way, since you have rights on the project, you should be able to merge your own pull request. So, whenever you feel that everything is fine, don't hesitate to merge your **pull requests**.

**Comment by peacing** [comment]
Thanks! I'm still getting comfortable with using git, hopefully it'll become second-nature soon enough. I will also check out Landscape and Coveralls and merge when appropriate.

**Comment by josuebrunel** [comment]
Don't worry it will, I'm sure of that. You can even create your own accounts on those services if you want, then add your forked repository. Having a github account is enough to subscribe to those kind of services. Hope it helped

**Pull request merged**
